# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-08 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('date', models.DateTimeField(verbose_name='date about price')),
            ],
        ),
    ]
