# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STapp', '0006_auto_20180313_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krw_balance', models.IntegerField(default=0)),
                ('currency_balance', models.FloatField(default=0)),
                ('currency_price', models.IntegerField(default=0)),
                ('currency_price_changed', models.IntegerField(default=0)),
                ('total_balance', models.IntegerField(default=0)),
                ('sell_buy', models.CharField(default='none', max_length=50)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='STapp.CoinList')),
            ],
        ),
    ]
