# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-13 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STapp', '0004_auto_20180312_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CoinList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='btc', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='coinprices',
            name='name',
        ),
        migrations.AddField(
            model_name='coinaccount',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='STapp.CoinList'),
        ),
        migrations.AddField(
            model_name='coinprices',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='STapp.CoinList'),
        ),
    ]
